// Copyright (c) 2024 DSR Corporation, Denver, Colorado.
// https://www.dsr-corporation.com
// SPDX-License-Identifier: Apache-2.0

use clap::Parser;
use serde::Serialize;

#[derive(Parser)]
pub struct Cli {
    /// The type to generate
    #[arg(short, value_enum, default_value_t = GenerateType::Example)]
    pub type_: GenerateType,
    /// The paths to the directories where specification.yaml file is located
    #[arg(short, value_delimiter = ' ', num_args = 0.., require_equals = false)]
    pub paths: Vec<std::path::PathBuf>,
    /// Reference implementation the fixtures in `paths` were generated by.
    /// Controls how mock-salted disclosures are JSON-formatted before hashing,
    /// so digests match the reference's own serialization.
    #[arg(long, value_enum, default_value_t = Reference::Python)]
    pub reference: Reference,
}

#[derive(clap::ValueEnum, Clone, Debug, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Reference {
    Python,
    Js,
}


#[derive(clap::ValueEnum, Clone, Debug, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum GenerateType {
    Example,
    TestCase,
}